### PR TITLE
Enabled the admin dashboard page

### PR DESCRIPTION
**Pull request by rommeltorquator**
#### Added simple admin feature

[WIP] Other admin features like approve and reject buttons for newly created broker accounts.

## The Story
In this project, I realized that the admin dashboard page is very important to be implemented early on since that is the place where an admin can approve or reject a broker to conduct business in the app, that is why I started to build a simple admin dashboard. It only displays all buyers and brokers for now. Here is what I did in the PR.

- Enabled the sign in and sign out functionality for admin.
- Implemented an admin dashboard that displays all buyers and brokers.
- Restructured the navigation bar to accommodate the added buttons.

#### Admin sign in page
image
#### Admin dashboard page and admin sign out button
image

## Resources
https://dev.to/luchiago/multiple-foreign-keys-for-the-same-model-in-rails-6-7ml
http://www.adwaretech.com/blog/rails-migrations-in-a-nutshell

### CODE REVIEW

**Comment by jarencudilla** [comment]
Oi, chill still doing the RSpec!!! Now I have tons to test.

**Review by jarencudilla — COMMENTED** [review]
Thank you, good thing you made views. I'll include these updates on my next RSpec PR -- currently on making the tests for controllers.

**Review by analyn-cajocson — APPROVED** [review]

**Comment by rommeltorquator** [comment]
No worries. I know you can easily apply the necessary tests on those views.

**Review by jarencudilla — APPROVED** [review]
Love these changes!

**Pull request merged**
