### PR TITLE
Created Models for Transaction, Stock and Broker_stock

### PR DESCRIPTION
**Pull request by jarencudilla**
## The Story
I created models for Transaction, Stock and Broker_stock
From the schema we discussed earlier :

- Created Stock model 
- Created Broker_stock model with reference to transactions 
- Created Transaction model with reference to users
- Associated transactions with users and broker_stocks

## Screenshots

screenshot 101

screenshot 103

### CODE REVIEW

**Comment by rommeltorquator** [comment]
Pending for pull request approval. Waiting for the rubocop tests to be fixed.

**Comment by jarencudilla** [comment]
Done Fixed rubocop errors

**Review by rommeltorquator — APPROVED** [review]
Please check the error in the database portion.

**Review by rommeltorquator — CHANGES_REQUESTED** [review]
Please fix the rubocop related error messages.

**Comment by jarencudilla** [comment]
closed due to errors, and will issue new PR with correct branch name and syntax

**Pull request closed without merging**
